Repository Wanted-Pre-Onboarding-Team-E/geography-based-restaurant-recommendation, pull requests merged in 2023-11, with the labels that each got.

#7 데이터베이스 마이그레이션
  package-lock.json
  package.json
  src/database/data-source.ts
  src/database/migrations/1698745525132-wanted.ts
  start.bat
  start.sh
Labels: enhancement

#11 사용자 회원가입 및 로그인 API
  package-lock.json
  package.json
  src/entity/user.entity.ts
  src/enum/failType.enum.ts
  src/enum/successType.enum.ts
  src/feature/auth/auth.controller.ts
  src/feature/auth/auth.module.ts
  src/feature/auth/auth.service.ts
  src/feature/auth/dto/signInUser.dto.ts
  src/feature/auth/dto/signUpUser.dto.ts
  src/feature/auth/guard/jwtAuth.guard.ts
  src/feature/auth/strategy/jwt.strategy.ts
  src/feature/user/user.lib.ts
  src/feature/user/user.module.ts
Labels: enhancement, good first issue

#9 맛집 평가 API 생성
  package.json
  src/app.module.ts
  src/entity/restaurant.entity.ts
  src/entity/review.entity.ts
  src/enum/failType.enum.ts
  src/enum/successType.enum.ts
  src/feature/auth/auth.module.ts
  src/feature/custom/apiResult.ts
  src/feature/restaurant/dto/createReviewDto.ts
  src/feature/restaurant/restaurant.controller.ts
  src/feature/restaurant/restaurant.module.ts
  src/feature/restaurant/restaurant.service.ts
  src/feature/review/review.controller.ts
  src/feature/review/review.module.ts
  src/feature/review/review.service.ts
  src/main.ts
  test/unit/controller/review.controller.spec.ts
  test/unit/service/review.service.spec.ts
Labels: enhancement

#19 외부 공공데이터 호출 및 데이터 전처리 후 DB 저장(스케줄러 사용)
  .eslintrc.js
  .template.env
  package-lock.json
  package.json
  src/app.module.ts
  src/custom/apiResult.ts
  src/entity/restaurant.entity.ts
  src/enum/businessType.enum.ts
  src/enum/errorStatus.enum.ts
  src/enum/externalApiType.enum.ts
  src/enum/failType.enum.ts
  src/feature/externalApi/externalApi.lib.ts
  src/feature/externalApi/externalApi.module.ts
  src/feature/restaurant/restaurant.lib.ts
  src/feature/restaurant/restaurant.service.ts
  src/feature/scheduler/scheduler.module.ts
  src/feature/scheduler/scheduler.service.ts
Labels: enhancement

#24 시군구 및 맛집 조회 API
  csv/sgg_lat_lon.csv
  package-lock.json
  package.json
  src/app.module.ts
  src/database/migrations/1698745525132-wanted.ts
  src/entity/restaurant.entity.ts
  src/enum/failType.enum.ts
  src/enum/successType.enum.ts
  src/feature/auth/auth.controller.ts
  src/feature/city/city.controller.ts
  src/feature/city/city.module.ts
  src/feature/city/city.service.ts
  src/feature/externalApi/externalApi.lib.ts
  src/feature/restaurant/dto/createReview.dto.ts
  src/feature/restaurant/dto/getRestaurant.dto.ts
  src/feature/restaurant/restaurant.controller.ts
  src/feature/restaurant/restaurant.module.ts
  src/feature/restaurant/restaurant.service.ts
  src/feature/review/review.controller.ts
  src/feature/review/review.service.ts
  src/feature/scheduler/scheduler.service.ts
  test/unit/controller/review.controller.spec.ts
Labels: enhancement

#32 맛집 상세 정보 고도화
  package-lock.json
  package.json
  src/app.module.ts
  src/feature/restaurant/restaurant.service.ts
Labels: enhancement

#35 기타 이슈 내용 수정
  src/feature/city/city.controller.ts
  src/feature/city/city.service.ts
  src/feature/restaurant/restaurant.controller.ts
  src/feature/restaurant/restaurant.service.ts
  src/feature/user/dto/updateUserLocation.dto.ts
  src/feature/user/user.controller.ts
  src/feature/user/user.service.ts
Labels: bug
